#!/bin/bash

# svn wrapper to make it more user friendly in the CLI, like git
# can also be sourced in bashrc and aliased to svn for a faster experience on
# windows which is slow at starting new processes

# Print the SVN repository root directory in relative URL format (^/...)
_mysvn_reporoot()
{
    local root="$(svn info --show-item relative-url | sed -E 's;/(branches|trunk)/?.*$;;')"
    printf '%s' "$root" # don't expand $root if it's a valid format string
}

# wrapper that calls the "real" svn binary
_mysvn_exec()
{
    svn "$@"
}

# Expand all arguments starting with a "/" to the repo root, then launch svn
# Easier than doing "eval `svn sr`" and then run "svn .. $sr ..."
_mysvn_expandedpath()
{
    # avoid calling _mysvn_reporoot() unnecessarily
    local args=( "$@" )
    for arg in "$@"; do
        if [[ "$arg" == /* ]]; then
            args=( "${@/#\//$(_mysvn_reporoot)\/}" )
            break
        fi
    done
    _mysvn_exec "${args[@]}"
}

# Colored diff with bat if stdout is a terminal, print function names
_mysvn_diff()
{
    shift
    if [ -t 1 ]; then
        _mysvn_expandedpath diff -x -p "$@" | bat -p
    else
        _mysvn_expandedpath diff -x -p "$@"
    fi
}

# Diff using `delta` as output decorator.
_mysvn_deltadiff()
{
    [ ! -t 1 ] && return 1
    shift
    _mysvn_expandedpath diff -x -p "$@" | delta
}

# Diff using `delta` as output decorator with "side-by-side" view
_mysvn_2sidedeltadiff()
{
    [ ! -t 1 ] && return 1
    shift
    _mysvn_expandedpath diff -x -p "$@" | delta --side-by-side
}

# Like git diff --stat: show also how much every file changed using `diffstat`
_mysvn_diffstat()
{
    local w=${COLUMNS:-80}
    if [ -z "$w" -o "$w" -gt 100 ]; then
        w=100
    fi
    shift
    _mysvn_expandedpath diff "$@" | diffstat -C -w $w
}

# Use pager (-F: quit if stdin fits one screen)
_mysvn_usepager()
{
    _mysvn_exec "$@" | less -F
}

# Use pager and include line number in blame
_mysvn_blame()
{
    shift
    _mysvn_expandedpath blame "$@" | less -iFN
}

# Use pager and color output if using --diff svn option
_mysvn_log()
{
    shift
    declare -a args
    if [[ "$*" == *"--diff"* ]]; then
        # svn log --diff -c revNum ~~ git show
        _mysvn_expandedpath log "$@" | bat -p -l diff
    else
        _mysvn_expandedpath log "$@" | less -F
    fi
}

# "short" log. Similar to git log --oneline
_mysvn_shortlog()
{
    shift
    _mysvn_expandedpath log "$@" | ~/src/msvn/short-log | less -F
}

# Commit cmd with pre-commit hook support like in git
_mysvn_commit()
{
    local preCommitHook="$(_mysvn_exec info --show-item wc-root)/.svn/hooks/pre-commit"
    shift
    if [ ! -x "$preCommitHook" ] || "$preCommitHook" "$@"; then
        _mysvn_exec commit "$@"
    else
        echo commit aborted by pre-commit hook >&2
    fi
}

 # set Svn Root variable (to use it in other commands)
_mysvn_setrootvar()
{
    declare -g sr="$(_mysvn_reporoot)"
    printf "sr='%s' # svn root dir shortcut\n" "$sr"
}

_svn_completion_lazyload()
{
    source ~/src/msvn/completions.bash && return 124
}

_mysvn_print_completions()
{
    # complete svn directly and not msvn as they have the same options
    complete -F _svn_completion_lazyload -o bashdefault -o default svn

    # print declarations so caller can `eval` them to import them
    declare -f _svn_completion_lazyload
    complete -p svn
}

mysvn()
{
    case "$1" in
        blame)      _mysvn_blame "$@" ;;
        cat)        _mysvn_expandedpath "$@" ;;
        commit|ci)  _mysvn_commit "$@" ;;
        copy|cp)    _mysvn_expandedpath "$@" ;;
        delete|del) _mysvn_expandedpath "$@" ;;
        diff|di)    _mysvn_diff "$@" ;;
        ddiff|ddi)  _mysvn_deltadiff "$@" ;;
        sddi)       _mysvn_2sidedeltadiff "$@" ;;
        dstat|dst)  _mysvn_diffstat "$@" ;;
        export)     _mysvn_expandedpath "$@" ;;
        help)       _mysvn_usepager "$@" ;;
        log)        _mysvn_log "$@" ;;
        slog)       _mysvn_shortlog "$@" ;;
        ls)         _mysvn_expandedpath "$@" ;;
        merge)      _mysvn_expandedpath "$@" ;;
        remove|rm)  _mysvn_expandedpath "$@" ;;
        status|stat|st) _mysvn_usepager "$@" ;;
        switch|sw)  _mysvn_expandedpath "$@" ;;
        sr)         _mysvn_setrootvar "$@" ;;

        completions) _mysvn_print_completions ;;

        # handle other commands using true svn directly
        *)          _mysvn_exec "$@" ;;
    esac
}

# if not sourced, invoke the function
if ! (return 0 2>/dev/null); then
    mysvn "$@"
fi
