#!/bin/bash

# this is an example pre-commit hook script
# to use it, copy it to the .svn/hooks/ dir on your repo and ensure it can be executed
#
# This example will abort any commits whose diff contain any "forbidden" word

# list of words that cannot be committed
blacklist='fixme todo debug'

# redirect stdout to stderr
exec 1>&2

declare -a filelist
declare -a changelist

for arg in "$@"; do
  if [ "$arg" = '--cl' -o "$arg" = '--changelist' ]; then
    changelist=( '--cl' )
  elif [ "${#changelist[@]}" = 1 ]; then
    changelist+=( "$arg" )
  elif [ -e "$arg" ]; then
    filelist+=("$arg")
  fi
done

if [ ${#filelist[@]} -eq 0 ]; then
  filelist+=(".")
fi

difflist="$(svn diff -x -U0 "${filelist[@]}" "${changelist[@]}" )"
if grep -qiE "^\\+.*(${blacklist// /|})" <<< "$difflist"; then
  echo ${blacklist// /, } comments found:
  echo
  grep -iEe "^\\+.*(${blacklist// /|})" -e '^index:' <<< "$difflist" \
    | grep --color=always -ie ${blacklist// / -e } -B 1

  exit 1
fi
